### ISSUE TITLE
Sort out naming in XDMFFile method names

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#20]
From @blechta 

It has been agreed in a discussion that following renaming scheme is favourable

```
class XDMFFile:
    read_checkpoint() -> read()
    write_checkpoint() -> write()
    write() -> write_vertex_values()
```

Arguably `write_vertex_values()` could be removed once support for `write_checkpoint()` format in Paraview is packaged and distributed well. User can instead do more explicit operation involving some kind of interpolation or projection.

See https://bitbucket.org/fenics-project/dolfinx/issues/27/sort-out-naming-in-xdmffile for comments.

**Comment by michalhabera** [comment]
Addressed in https://github.com/FEniCS/dolfinx/tree/michal/sort-naming-xdmf
Instead of `read_checkpoint -> read` I applied `read_checkpoint -> read_function` to stay consistent with the rest of XDMF, where write is implicit and read is explicit (argument type in name).

But I don't like the wrapping in `python/dolfin/io.py` ... Did you guys (@garth-wells @chrisrichardson ) found a better way for this `dolfin.function.function.Function` casting?

**Comment by garth-wells** [comment]
@michalhabera I'm tending toward nothing in the `cpp` namespace being 'public'. All Python functionality would be implemented in Python with calls the backend. In this case we would not have to do anything casting in the pybind11 code.

This would also help with documentation. The Python and C++ interface would have their own docs.

**Comment by garth-wells** [comment]
Some will just be `import foo as bar`.

I don't expect it will be more work that what we already have, and likely less . In cases it will be less because we won't have to manage something one on of two things, e.g. a `dolfin.function.Function` or a `dolfin.cpp.function.Function`.

**Comment by michalhabera** [comment]
The naming above is too complicated. We need to keep things easy.
With the proper and fast interpolation (https://github.com/FEniCS/dolfinx/issues/161) most of the under-the-hood interpolation should happen explicitly by user action. 

And in order to avoid new function memory allocation just to IO, we can have some local, cell-wise interpolation methods. These can work as iterators and cell by cell flush the values.

**Comment by jorgensd** [comment]
@garth-wells  this is not resolved. Right now we have removed write_checkpoint, and we have to reintroduce it at some point.
