### ISSUE TITLE
[BUG]: test_timer.py test_context_manager_named sometimes fails in complex build

### ISSUE THREAD

**Issue by drew-parsons** [FEniCS/dolfinx#2946]
### Summarize the issue

Python unit test common/test_timer.py is sometimes failing test_context_manager_named in the complex number build with PETSc 3.19 on amd64.

Full test log at https://ci.debian.net/data/autopkgtest/testing/amd64/f/fenics-dolfinx/41398806/log.gz

The discrepancy is small, should the tolerance in the test be relaxed?

### How to reproduce the bug

In principle
`PETSC_DIR=/usr/lib/petscdir/petsc-complex SLEPC_DIR=/usr/lib/slepcdir/slepc-complex pytest-3 -v python/test/unit/common/test_timer.py`
though it does not fail on my own local machine.

### Output (Python)

```bash
2193s __________________________ test_context_manager_named __________________________
2193s 
2193s     def test_context_manager_named():
2193s         """Test that named Timer works as context manager"""
2193s         task = "test_context_manager_named_str"
2193s     
2193s         # Execute task in the context manager
2193s         t = common.Timer(task)
2193s         sleep(0.05)
2193s >       assert t.elapsed()[0] >= 0.05
2193s E       assert 0.04 >= 0.05
2193s 
2193s python/test/unit/common/test_timer.py:21: AssertionError
```

### Version

0.7.2

### DOLFINx git commit

debian build 1:0.7.3-2
(git commit 25db9a743ef95a78f686f05e38607aa18281b0d6)

### Installation

debian build 1:0.7.3-2 (debian unstable)

**Comment by drew-parsons** [comment]
Given the nature of the test, simply testing timings, it doesn't really make sense that it's actually related to the complex build or to PETSc 3.19.  It must be a question of the precision of the values returned by `t.elapsed()`, or of the precision in the execution of `sleep(0.05)`, with some random variation in the results.

**Comment by drew-parsons** [comment]
dolfinx's Timer is  boost::timer::cpu_timer.  The Boost version used here is 1.83.0.

**Comment by drew-parsons** [comment]
Showing the randomness of the discrepancy, the test passed on a repeat run,
https://ci.debian.net/data/autopkgtest/testing/amd64/f/fenics-dolfinx/41401318/log.gz

**Comment by drew-parsons** [comment]
For what it's worth, legacy dolfin is also affected, https://ci.debian.net/data/autopkgtest/unstable/amd64/d/dolfin/41436063/log.gz
I guess it's happening because of some change in Boost 1.83.

**Comment by jhale** [comment]
Our test is the only thing that looks strange here 🤭

**Comment by garth-wells** [comment]
Hopefully fixed by #2946.

**Comment by drew-parsons** [comment]
Great.  Once PETSc 3.19 has settled in Debian, I'll test the patch, then adapt it to legacy dolfin.

**Comment by drew-parsons** [comment]
I guess we need to reopen this bug.
From 0.8.0 (git head)
```
________________________ test_context_manager_anonymous ________________________

    def test_context_manager_anonymous():
        """Test that anonymous Timer works as context manager"""
        with common.Timer() as t:
            sleep(0.05)
>           assert t.elapsed()[0] > 0.045
E           assert 0.04 > 0.045

test/unit/common/test_timer.py:34: AssertionError
```

**Comment by francesco-ballarin** [comment]
FYI, yesterday I undid the patch you had on this test, hoping that this was fixed. 

In the former patch sleep(0.05) was increased to sleep(0.1), and the margin for error was 0.015 instead of 0.005. I guess we can reinstate the former patch, but that still doesn't explain why failure happens on some systems and not others.

**Comment by drew-parsons** [comment]
I'm updating the debian patch.  Looks like the larger margin for error will be needed. We can make another PR here.

**Comment by jorgensd** [comment]
@drew-parsons  should we close this PR, or do we need to increase the sleep to test timers?

**Comment by drew-parsons** [comment]
Still fails (0.8.0) without the patch, so need to increase the sleep.
Current [debian patch](https://salsa.debian.org/science-team/fenics/fenics-dolfinx/-/blob/master/debian/patches/test_timing_precision.patch?ref_type=heads) is
```
Index: fenics-dolfinx/python/test/unit/common/test_timer.py
===================================================================
--- fenics-dolfinx.orig/python/test/unit/common/test_timer.py   2024-04-12 19:19:28.134428505 +0200
+++ fenics-dolfinx/python/test/unit/common/test_timer.py        2024-04-12 19:23:01.340519947 +0200
@@ -10,6 +10,9 @@
 
 from dolfinx import common
 
+# resolution of the Timer is not precise,
+# need to allow some tolerance
+timing_resolution = 0.015
 
 def test_context_manager_named():
     """Test that named Timer works as context manager"""
@@ -17,8 +20,8 @@
 
     # Execute task in the context manager
     t = common.Timer(task)
-    sleep(0.05)
-    assert t.elapsed()[0] > 0.045
+    sleep(0.1)
+    assert t.elapsed()[0] >= 0.1 - timing_resolution
     del t
 
     # Check timing
@@ -30,5 +33,5 @@
 def test_context_manager_anonymous():
     """Test that anonymous Timer works as context manager"""
     with common.Timer() as t:
-        sleep(0.05)
-        assert t.elapsed()[0] > 0.045
+        sleep(0.1)
+        assert t.elapsed()[0] >= 0.1 - timing_resolution
```

**Comment by drew-parsons** [comment]
I made PR #3430

**Comment by drew-parsons** [comment]
Hmm, something went wrong with my repo sync, so I cancelled my PR. I see that actual HEAD has already set a larger tolerance (PR #3193) so almost certainly that's sufficient now (I haven't tested 0.9/HEAD myself).

**Comment by garth-wells** [comment]
#3484 removes Boost timer and test has been changed, so hopefully this is fixed.
